stages: #  of stages for jobs, and their order of execution
  - build

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo -e "\nСобираем проект...\n"
    - docker compose down
    - mvn clean package
    - mvn -f ./config-service/pom.xml clean package
    - mvn -f ./discovery-service/pom.xml clean package
    - mvn -f ./admin-service/pom.xml clean package
    - mvn -f ./gateway-service/pom.xml clean package
    - docker-compose up -d --build
    - echo -e "\nЗапустилося!!\n"
  rules:
    - if: ($CI_COMMIT_BRANCH == "master")
