server:
  port: 8108
spring:
  application:
    name: admin-service
  security:
    user:
      name: admin
      password: admin
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
logging:
  file:
    name: logs/info.log
