spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mmt
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mmtr-auth-url: http://localhost:8083/