server:
  port: 8103
spring:
  application:
    name: auth-service
  boot:
    admin:
      client:
        url: http://admin-service/
        username: admin
        password: admin
  datasource:
    url: jdbc:postgresql://10.10.0.14:5432/mmt
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.0.12:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
logging:
  file:
    name: logs/info.log
mmtr-auth-url: http://10.10.0.15:8080/
secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret