server:
  port: 8103
spring:
  application:
    name: auth-service
  boot:
    admin:
      client:
        url: http://admin-service/
        username: admin
        password: admin
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
logging:
  file:
    name: logs/info.log
secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret