server:
  port: 8103
grpc:
  client:
    people:
      address: discovery:///person-service
      negotiationType: PLAINTEXT
spring:
  application:
    name: auth-service
  boot:
    admin:
      client:
        url: http://admin-service/
        username: admin
        password: admin
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
logging:
  file:
    name: logs/info.log
access-token-secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
refresh-token-secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
access-token-life-time-seconds: 900  # 15 minutes
refresh-token-life-time-seconds: 1209600  # 2 weeks
