spring:
  datasource:
    url: jdbc:postgresql://10.10.0.14:5432/mmt
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.0.12:8761/eureka
mmtr-auth-url: https://my.mmtr.ru/
