spring:
  datasource:
    url: jdbc:postgresql://10.10.0.14:5432/auth_db
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: 10.10.0.16:29092
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.0.12:8761/eureka
mmtr-auth-url: http://10.10.0.15:8080/
