spring:
  datasource:
    password: pass
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/mmt
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
