server:
  port: 8105
spring:
  application:
    name: keeper-personal-cabinet-service
  boot:
    admin:
      client:
        url: http://admin-service/
        username: admin
        password: admin
  datasource:
    password: pass
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://10.10.0.14:5432/mmt
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: galaxyCacheTopic
    bootstrap-servers: 10.10.0.16:29092
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.0.12:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
logging:
  file:
    name: logs/info.log
secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
