spring:
  datasource:
    password: pass
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://10.10.0.14:5432/person_db
  kafka:
    bootstrap-servers: 10.10.0.16:29092
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://10.10.0.12:8761/eureka
