server:
  port: 4401
spring:
  application:
    name: gateway-service
  profiles:
    default: local
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: person-service
          uri: lb://person-service
          predicates:
            - Path=/api/v1/person-app/**
        - id: galaxy-service
          uri: lb://galaxy-service
          predicates:
            - Path=/api/v1/galaxy-app/**
        - id: planet-service
          uri: lb://planet-service
          predicates:
            - Path=/api/v1/planet-app/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/v1/course-app/**
        - id: course-registration-service
          uri: lb://course-registration-service
          predicates:
            - Path=/api/v1/course-registration-app/**
        - id: progress-service
          uri: lb://progress-service
          predicates:
            - Path=/api/v1/progress-app/**
        - id: homework-service
          uri: lb://homework-service
          predicates:
            - Path=/api/v1/homework-app/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/api/v1/feedback-app/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
