server:
  port: 8101
grpc:
  client:
    people:
      address: discovery:///person-service
      negotiationType: PLAINTEXT
    explorers:
      address: discovery:///person-service
      negotiationType: PLAINTEXT
    keepers:
      address: discovery:///person-service
      negotiationType: PLAINTEXT
spring:
  application:
    name: galaxy-service
  profiles:
    default: local
  mvc:
    log-resolved-exception: false
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        enable_lazy_load_no_trans: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      enabled: true
logging:
  file:
    name: logs/info.log
access-token-secret-key: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
