package org.example.courseregistration.service;

import org.example.courseregistration.model.CourseRegistrationRequestKeeper;
import org.example.courseregistration.model.CourseRegistrationRequestKeeperStatus;
import org.example.courseregistration.model.CourseRegistrationRequestKeeperStatusType;

public interface CourseRegistrationRequestKeeperStatusService {
    CourseRegistrationRequestKeeperStatus findCourseRegistrationRequestKeeperStatusByStatus(CourseRegistrationRequestKeeperStatusType status);

    void updateCourseRegistrationRequestKeeperStatus(CourseRegistrationRequestKeeper keeperResponse, CourseRegistrationRequestKeeperStatusType status);
}
